### ISSUE TITLE
Please review your commands with recent BMP

### ISSUE THREAD

**Issue by UweBonnes** [AndruPol/nrf52832-recover#3]
Please review our commands with a recent BMP firmware. BMP should now be able to program nrf52832 too. No need for OpenOCD.

**Comment by AndruPol** [comment]
ok, thanks!

**Comment by UweBonnes** [comment]
You still propose that people use OpenOCD for flashing? Why not the BMP already connected?

**Comment by AndruPol** [comment]
i use openocd about 5 years and it's work well. i have not BMP and reflashed my black pill only for unlock nrf52. i am going to try BMP with eclipse cdt now.

**Comment by AndruPol** [comment]
most likely it will be a black pill or st-link clone with bmp firmware)
